name: terraform tests

on:
  push:
    branches:
      - main

jobs:
  terraform-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Terraform Repo
        uses: actions/checkout@v4

      - name: Lint Terraform
        uses: actionshub/terraform-lint@main
      
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@main
        with:
          directory: tf
          framework: terraform 